# Generated by Django 5.0.6 on 2024-05-16 08:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_name', models.TextField(max_length=30)),
                ('admin_email', models.TextField(max_length=30)),
            ],
        ),
    ]
