# Generated by Django 5.0.6 on 2024-05-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_name',
            field=models.TextField(default='School', max_length=30),
            preserve_default=False,
        ),
    ]
